version: "0.0.1"
services:
  mirai:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 11451:11451
    resources:
      requests:
        cpu: 1000m
        memory: 3Gi
    volumes:
      - .:/root/MCL